name: Node.js CI

on:
  push:
    branches: [sohozmeal_backend]

env:
  PORT: ${{secrets.PORT}}
  NODE_ENV: ${{secrets.NODE_ENV}}
  SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  DB_URI_CLOUD: ${{secrets.DB_URI_CLOUD}}
  API_KEY: ${{secrets.API_KEY}}
  SENDER_ID: ${{secrets.SENDER_ID}}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to target directory
        run: |
          sudo rm -rf /home/mist/osmany_hall_backend/* # Remove existing files
          sudo cp -r . /home/mist/osmany_hall_backend/ # Copy new files
          sudo chown -R $USER:$USER /home/mist/osmany_hall_backend # Adjust permissions

      - name: Install dependencies
        run: npm ci
        working-directory: /home/mist/osmany_hall_backend

      - name: Restart PM2 process
        run: pm2 restart sohozmeal -a
